### PR TITLE
Remove `TRACK_NOTIF` and `RECEIVED_NOTIF` intents

### LINKED ISSUE #10: Outbound crashes on Android 8+
Outbound doesn't show any notification and crashes the app (if it is in the background) whenever you send a push notification:

```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=DISPLAY_NOTIF pkg=* (has extras) }: app is in background uid UidRecord{e2eb6b u0a166 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
       at io.outbound.sdk.OutboundPushReceiver.handleOutboundIntent(OutboundPushReceiver.java:1087)
```

### PR DESCRIPTION
**Pull request by ryan-scott-dev**
This PR fixes #10.

This PR removes using an intent for performing notification callbacks to our server, and instead attempts to immediately make the requests when handling the notification.
If FCM stops execution after 10s, then due to the HTTP request functionality the requests will be made when the app is in the foreground next or when another notification is received.

The [Migration Guide](https://github.com/outboundio/android-sdk/blob/360ed3004aa5e875d9fa0f5ae062f65a9f364035/docs/migrating.md) provides more information on what changes are needed for the new version of the SDK.

### Changes:
1. Removed `X.outbound.action.TRACK_NOTIF` and `X.outbound.action.RECEIVED_NOTIF` intents.
2. Removed `OutboundIntentHandler`.
3. Rename some variables related to the uninstall tracker to be more explicit of its purpose.

### Remaining Work
- Update [Android SDK documentation](https://developer.zendesk.com/embeddables/docs/outbound/android)
- Release 0.4.0 version

### CODE REVIEW

**Review by ashmckenzie — APPROVED** [review]
Terrific! 👍

File: src/main/java/io/outbound/sdk/RequestHandler.java [hunk 1]
```diff
@@ -64,6 +64,22 @@ public void processAfterDelay(OutboundRequest request, long delayMillis) {
...
+    public void processImmediately(OutboundRequest request) {
+        ensureInitialized();
+
+        if (canProcess()) {
+            Status immediateSendStatus = sendQueuedRequest(request);
+            if (immediateSendStatus != Status.SUCCESS) {
+                request.incAttempts();
+                queue(request);
+            } else {
+                storage.remove(request.getId());
```
Comment (maleckai) [inline src/main/java/io/outbound/sdk/RequestHandler.java]: @ryan-scott-dev doesn't think this is needed.

File: src/main/java/io/outbound/sdk/RequestHandler.java [hunk 2]
```diff
@@ -64,6 +64,22 @@ public void processAfterDelay(OutboundRequest request, long delayMillis) {
         handler.postDelayed(buildRunnableRequest(request), delayMillis);
     }
 
+    public void processImmediately(OutboundRequest request) {
+        ensureInitialized();
+
+        if (canProcess()) {
+            Status immediateSendStatus = sendQueuedRequest(request);
```
Comment (maleckai) [inline src/main/java/io/outbound/sdk/RequestHandler.java]: We should try more than once here before queuing.

**Review by maleckai — COMMENTED** [review]
Looking good. 👍  once you tackle the ☝️  two things you mentioned in the walkthrough.

File: src/main/java/io/outbound/sdk/RequestHandler.java (hunk 2 above)
Comment (ryan-scott-dev) [reply src/main/java/io/outbound/sdk/RequestHandler.java]: I thought about this a bit more, I think I might change it so that if it fails it then reschedules the Firebase job rather than using queue.

**Comment by ryan-scott-dev** [comment]
I've changed the approach to now try and make the requests immediately when handling the push message, and if Android stops the execution after 10s we fall back on the existing request persistence so that its reattempted when the app is next in the foreground or when another notification is received.

File: src/main/java/io/outbound/sdk/OutboundMessagingService.java [hunk 3]
```diff
@@ -83,13 +84,14 @@ private void handleOutboundMessage(RemoteMessage message) {
...
 
-            // TODO handle exceptions? thread?
             onNotificationDisplayed(outboundNotification);
         }
 
-        Intent intent = new Intent();
-        intent.putExtras(bundle);
-        new OutboundIntentHandler().handleIntent(this, intent);
+        if (outboundNotification.isUninstallTracker()) {
+            OutboundClient.getInstance().trackNotification(this, outboundNotification.getInstanceId());
```
Comment (ashmckenzie) [inline src/main/java/io/outbound/sdk/OutboundMessagingService.java]: Possibly assign `OutboundClient.getInstance()`  to a local variable

**Review by ashmckenzie — APPROVED** [review]
👍

**Review by maleckai — APPROVED** [review]
👍
